"""vamos cron-install / cron-uninstall / cron-list — manage scheduled tasks from crons.yml.

On Mac/Linux: writes a marker-bracketed block to the user's crontab.
On Windows: dispatches to Task Scheduler via schtasks.exe (see win_tasks.py).
The CLI commands work the same way on both.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

from .config import ROOT
from . import win_tasks

MARKER_BEGIN = "# >>> vamos managed >>>"
MARKER_END = "# <<< vamos managed <<<"


def load_crons() -> list[dict]:
    p = ROOT / "crons.yml"
    if not p.exists():
        # Fall back to .example file with a warning so first-run users see something
        p = ROOT / "crons.yml.example"
        if not p.exists():
            return []
    try:
        data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        print(f"crons.yml is invalid YAML: {exc}", file=sys.stderr)
        return []
    return data.get("crons", []) or []


def enabled_cron_entries() -> list[dict]:
    return [c for c in load_crons() if c.get("enabled") and c.get("schedule") != "launchd"]


def launchd_entries() -> list[dict]:
    return [c for c in load_crons() if c.get("enabled") and c.get("schedule") == "launchd"]


def render_crontab_block(working_dir: Path) -> str:
    """Render the vamos-managed crontab block as a single string."""
    entries = enabled_cron_entries()
    lines = [MARKER_BEGIN, "# Generated by `vamos cron-install`. Do not edit by hand."]
    if not entries:
        lines.append("# (no enabled cron entries in crons.yml)")
    bin_dir = (working_dir / ".venv" / "bin").resolve()
    use_venv_path = (bin_dir / "vamos").exists()
    for c in entries:
        cmd = c["command"]
        if use_venv_path and cmd.startswith("vamos "):
            cmd = f"{bin_dir}/{cmd}"
        # Ensure logs go somewhere
        log_path = working_dir / "logs" / f"{c['name']}.log"
        line = (
            f"{c['schedule']} cd {working_dir} && {cmd} "
            f">> {log_path} 2>&1"
        )
        lines.append(f"# {c.get('description','')}")
        lines.append(line)
    lines.append(MARKER_END)
    return "\n".join(lines)


def get_current_crontab() -> str:
    try:
        return subprocess.check_output(["crontab", "-l"], stderr=subprocess.DEVNULL).decode()
    except subprocess.CalledProcessError:
        # Empty crontab on first install
        return ""


def strip_existing_block(crontab: str) -> str:
    if MARKER_BEGIN not in crontab:
        return crontab
    out_lines: list[str] = []
    skipping = False
    for line in crontab.splitlines():
        if line.strip() == MARKER_BEGIN:
            skipping = True
            continue
        if line.strip() == MARKER_END:
            skipping = False
            continue
        if not skipping:
            out_lines.append(line)
    return "\n".join(out_lines).rstrip() + "\n"


def write_crontab(content: str) -> None:
    proc = subprocess.run(
        ["crontab", "-"], input=content, text=True, capture_output=True, check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"crontab write failed: {proc.stderr}")


def cmd_install(args, cfg) -> int:
    if sys.platform == "win32":
        return _cmd_install_windows(args, cfg)
    return _cmd_install_unix(args, cfg)


def cmd_uninstall(args, cfg) -> int:
    if sys.platform == "win32":
        return _cmd_uninstall_windows(args, cfg)
    return _cmd_uninstall_unix(args, cfg)


def cmd_list(args, cfg) -> int:
    crons = load_crons()
    if not crons:
        print("No crons.yml found (or empty). Copy crons.yml.example to crons.yml.")
        return 0
    print(f"{'NAME':<35}  {'SCHEDULE':<20}  ENABLED  COMMAND")
    print("-" * 100)
    for c in crons:
        en = "yes" if c.get("enabled") else "no"
        sched = c.get("schedule", "?")
        print(f"{c['name']:<35}  {sched:<20}  {en:<7}  {c.get('command','')}")

    # Show what's actually installed on the system
    print()
    if sys.platform == "win32":
        installed = win_tasks.list_tasks()
        if installed:
            print(f"Currently installed in Task Scheduler ({len(installed)}):")
            for t in installed:
                print(f"  - {t}")
        else:
            print("No vamos- tasks currently in Task Scheduler.")
    else:
        current = get_current_crontab()
        if MARKER_BEGIN in current:
            block_lines = []
            in_block = False
            for line in current.splitlines():
                if line.strip() == MARKER_BEGIN:
                    in_block = True
                    continue
                if line.strip() == MARKER_END:
                    in_block = False
                    continue
                if in_block:
                    block_lines.append(line)
            n = sum(1 for line in block_lines
                    if line.strip() and not line.strip().startswith("#"))
            print(f"Currently in crontab ({n} entry/entries — `crontab -l` to see).")
        else:
            print("No vamos-managed block currently in crontab.")
    return 0


# ---------------------------------------------------------------------------
# Unix (cron) implementation
# ---------------------------------------------------------------------------


def _cmd_install_unix(args, cfg) -> int:
    if not shutil.which("crontab"):
        print("crontab not found on PATH.", file=sys.stderr)
        return 1
    new_block = render_crontab_block(ROOT)
    base = strip_existing_block(get_current_crontab())
    combined = (base.rstrip() + "\n\n" + new_block + "\n") if base.strip() else (new_block + "\n")
    if args.dry_run:
        print(combined)
        return 0
    write_crontab(combined)
    n = len(enabled_cron_entries())
    print(f"Installed {n} cron entry(ies).")
    if launchd_entries():
        print("\nNote: the following entries use schedule=launchd and were NOT added to cron.")
        print("Set them up manually as launchd LaunchDaemons or systemd services:")
        for c in launchd_entries():
            print(f"  - {c['name']}: {c['command']}")
    return 0


def _cmd_uninstall_unix(args, cfg) -> int:
    if not shutil.which("crontab"):
        print("crontab not found on PATH.", file=sys.stderr)
        return 1
    base = strip_existing_block(get_current_crontab())
    if args.dry_run:
        print(base)
        return 0
    write_crontab(base)
    print("Removed vamos-managed cron block.")
    return 0


# ---------------------------------------------------------------------------
# Windows (Task Scheduler) implementation
# ---------------------------------------------------------------------------


def _cmd_install_windows(args, cfg) -> int:
    if not win_tasks.has_schtasks():
        print("schtasks.exe not available — are you actually on Windows?", file=sys.stderr)
        return 1
    entries = enabled_cron_entries() + launchd_entries()
    if not entries:
        print("No enabled crons in crons.yml.")
        return 0
    if args.dry_run:
        print("Would install the following Task Scheduler entries:")
        for c in entries:
            spec = win_tasks.translate_cron(c["schedule"])
            status = "OK" if spec else "UNSUPPORTED PATTERN"
            print(f"  [{status}] {win_tasks.VAMOS_TASK_PREFIX}{c['name']}  ({c['schedule']})")
        return 0
    n_ok, n_skip = 0, 0
    for c in entries:
        ok, msg = win_tasks.install_task(
            name=c["name"],
            command=c["command"],
            expr=c["schedule"],
            working_dir=str(ROOT),
        )
        if ok:
            print(f"  installed: {win_tasks.VAMOS_TASK_PREFIX}{c['name']}")
            n_ok += 1
        else:
            print(f"  skipped {c['name']}: {msg}", file=sys.stderr)
            n_skip += 1
    print(f"\nInstalled {n_ok} task(s); skipped {n_skip}.")
    return 0


def _cmd_uninstall_windows(args, cfg) -> int:
    if not win_tasks.has_schtasks():
        print("schtasks.exe not available.", file=sys.stderr)
        return 1
    if args.dry_run:
        print(f"Would remove: {win_tasks.list_tasks()}")
        return 0
    n, removed = win_tasks.uninstall_all()
    if removed:
        print(f"Removed {n} task(s):")
        for name in removed:
            print(f"  - {name}")
    else:
        print("No vamos- tasks found in Task Scheduler.")
    return 0
