"""daily-comments cleaner.

Generates a one-line status comment for a ticket that's missing one. Reads
the ticket's title, recent comments, and linked PRs to ground the message.
The actual comment text is generated by Claude via call_claude.

Falls back to a generic "still in progress" comment if the LLM is unavailable.
"""
from __future__ import annotations

import logging

from ...cleaner import Action, Proposal
from ...config import Config
from ...core.report import Finding
from ...core.snapshot import TeamSnapshot
from ...llm import call_claude, LLMError

log = logging.getLogger(__name__)

RULE_ID = "daily-comments"


def propose(finding: Finding, snapshot: TeamSnapshot, cfg: Config) -> Proposal | None:
    if not finding.ticket_id:
        return None
    w = next((x for x in snapshot.work_items if x.id == finding.ticket_id), None)
    if not w:
        return None

    # Build context for the LLM
    recent_comments = snapshot.comments_by_item.get(w.id, [])[-3:]  # last 3 comments
    comment_lines = [
        f"  [{c.created.strftime('%m-%d %H:%M')} · {c.author}] {c.text[:200]}"
        for c in recent_comments
    ]
    linked_prs = snapshot.prs_for_item(w.id)
    pr_lines = [f"  PR #{pr.id} ({pr.repo}) — {pr.title}" for pr in linked_prs]

    prompt = f"""You are vamos, an automated assistant filling in a missing daily status comment on an Azure DevOps ticket.

The ticket's assignee forgot to post a daily status. Write a SHORT (1-2 sentences, 200 chars max) status comment from their perspective. Be neutral and factual — describe what's happening, not what they should do. If you don't have enough signal, say "Still in progress, no update today" or similar.

Ticket: #{w.id} — {w.title}
State: {w.state}  ·  Type: {w.type}  ·  Priority: P{w.priority}
Assignee: {w.assigned_to or '(unassigned)'}

Recent comments (most recent last):
{chr(10).join(comment_lines) if comment_lines else '  (none)'}

Linked PRs:
{chr(10).join(pr_lines) if pr_lines else '  (none)'}

Output ONLY the comment text — no preamble, no quotes, no markdown. Just the sentence(s) the assignee would post.
"""

    try:
        suggested_text = call_claude(prompt, claude_bin=cfg.claude_bin, timeout=120).strip()
        if suggested_text.startswith('"') and suggested_text.endswith('"'):
            suggested_text = suggested_text[1:-1]
        confidence = "medium"
    except LLMError as exc:
        log.warning("daily-comments cleaner: LLM call failed (%s); using fallback", exc)
        suggested_text = "Still in progress, no notable update today."
        confidence = "low"

    final_text = f"[vamos hygiene clean] {suggested_text}"

    return Proposal(
        finding=finding,
        rationale=(
            f"Generate the missing daily status comment from recent ticket activity "
            f"({len(recent_comments)} prior comment(s), {len(linked_prs)} linked PR(s))."
        ),
        actions=[Action(kind="comment", work_item_id=w.id, payload={"text": final_text})],
        confidence=confidence,
    )
